config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    resources :team_memberships
  end

  resources :presences

  resources :training_types

  resources :seasons do
  	resources :events
  	get :attendances, :on => :member
  end

  resources :members

  root to: 'home#index'

  devise_for :users
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :season
	belongs_to :event_type
	has_many :presences
	has_many :members, :through => :presences

	validates :event_type, presence: true
	validates :season, presence: true
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
	has_many :events

	validates :name, presence: true
end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :presences
	has_many :events, :through => :presences
	has_many :team_memberships
	has_many :teams, :through => :team_memberships
	
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :sex, presence: true, inclusion: [0,1]

	def full_name
		"#{first_name} #{last_name}"
	end

	def current_team
		team_participations.where(['start < ? AND (finish > ? OR finish IS NULL)', Time.now, Time.now]).first.try(:team)
	end
end

app/models/presence.rb
class Presence < ActiveRecord::Base
	belongs_to :member
	belongs_to :event

	PRESENCE_TYPES = {
		1 => 'Present',
		2 => 'Absent',
		3 => 'Extenuated',
		4 => 'Competition'
	}

	def type_name
		PRESENCE_TYPES[presence_type]
	end
end

app/models/season.rb
class Season < ActiveRecord::Base
	has_many :events
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :team_memberships
	has_many :members, :through => :team_memberships
	accepts_nested_attributes_for :team_memberships

	def current_members
		members.where('start < ? AND (finish > ? OR finish IS NULL)', Time.now, Time.now)
	end
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
	belongs_to :team
	belongs_to :member

	def active?
		now = Time.now
		(start.nil? || start < now) && (finish.nil? || finish > now)
	end

	# if no start date is given it is assumed that it is equal
	# to team founding date
	def start
		attribute(:start) || self.team.founded
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
	end

	def show
		@event = Event.find(params[:id])
		@presences = @event.presences.eager_load(:member)
	end

	def new
		@season = Season.find(params[:season_id])
		@event = @season.events.build
		@event.date = Date.today
	end

	def create
		@season = Season.find(params[:season_id])
		@event = @season.events.build(safe_params)
		if @event.save
			redirect_to season_event_path(@season, @event)
		else
			render :new
		end
	end

	def edit
		@season = Season.find(params[:season_id])
		@event = @season.events.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(safe_params)
			redirect_to season_event_path(@event.season_id, @event)
		else
			render :edit
		end
	end


	private
	def safe_params
		params.require(:event).permit(:title, :description, :date, :season_id, :event_type_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def index
		@members = Member.all
	end

	def show
		@member = Member.find(params[:id])
		@presences = @member.presences.joins(:event => :event_type).
			eager_load(:event => :event_type).order('events.date DESC')
		@attendance = AttendanceCalculator.new(@presences).calculate
	end

	def new
		@member = Member.new
	end

	def create
		@member = Member.new(safe_params)
		if @member.save
			redirect_to members_path
		else
			render :new
		end
	end


	def destroy
		member = Member.find(params[:id])
		member.destroy
		redirect_to members_path
	end

	private
	def safe_params
		params.require(:member).permit(:first_name, :last_name, :sex, :active, :active_since)
	end
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
	def index
		@seasons = Season.order(start: :desc)
	end

	def show
		@season = Season.find(params[:id])
		@events = @season.events.includes(:event_type).order(date: :desc)
		@event_types = EventType.where(id: @season.events.select(:event_type_id).uniq)
	end

	def attendances
		@season = Season.find(params[:id])
		@events = @season.events.order('date asc').includes(:presences)
		member_ids = @events.map{|t| t.presences.map(&:member_id) }.flatten.uniq
		@members = Member.where(id: member_ids).order('last_name, first_name')
		@member_presences = []
		@members.each do |member|
			presence_ary = []
			@events.each do |event|
				presence_ary << event.presences.select{|p| p.member_id == member.id }.first
			end
			attendance = AttendanceCalculator.new(presence_ary.compact).calculate[:total][:all]
			@member_presences << {member: member, presence: presence_ary, attendance: attendance}
		end
	end

	def new
		@season = Season.new
	end

	def create
		@season = Season.new(sanitized_params)
		if @season.save
			redirect_to seasons_path
		else
			render :new
		end
	end

	def edit
		@season = Season.find(params[:id])
	end

	def update
		@season = Season.find(params[:id])
		if @season.update_attributes(sanitized_params)
			redirect_to seasons_path
		else
			render :edit
		end
	end

	def destroy
		season = Season.find(params[:id])
		season.destroy
		redirect_to seasons_path
	end

	private
	def sanitized_params
		params.require(:season).permit(:name, :start)
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@teams = Team.all
	end

	def show
		@team = Team.find(params[:id])
		@memberships = @team.team_memberships.includes(:member)
	end

	def new
		@team = Team.new
		@team.team_memberships.build
	end

	def create
		@team = Team.new(safe_params)
		if @team.save
			redirect_to teams_path
		else
			render :new
		end
	end

	def edit
		@team = Team.find(params[:id])
	end

	def update
		@team = Team.find(params[:id])
		if @team.update_attributes(safe_params)
			redirect_to teams_path
		else
			render :edit
		end
	end

	private
	def safe_params
		params.require(:team).permit(:name, :founded, :active, :members)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def presence_class(presence)
    return "" if presence.nil?
    presence.type_name.downcase
  end

  def format_presence(presence)
    return "" if presence.nil?
    case presence.presence_type
      when 1 then t('presence.abbrev.present')
      when 2 then t('presence.abbrev.absent')
      when 3 then t('presence.abbrev.extenuated')
      when 4 then t('presence.abbrev.competition')
    end
  end

  def administration_links(params)
    render partial: 'shared/administration_links',
      locals: {edit_path: params[:edit], delete_path: params[:delete]}
  end

  def event_title(event)
    return event.title unless event.title.blank?
    "#{event.event_type.name}: #{event.date}"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
	def format_sex(sex)
		if sex == 0
			t('female')
		else
			t('male')
		end
	end

	def format_attendances(attendances)
		total = attendances.delete(:total)
		if attendances.keys.length <= 1
			return {partial: 'members/attendance_simple', locals: {attendance: total}}
		end
	end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/team_memberships_helper.rb
module TeamMembershipsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
  def memberships_to_show(team)
    memberships = team.team_memberships.includes(:member)
    team.active ? memberships.select{|m| m.active? } : memberships
  end
end

app/helpers/training_types_helper.rb
module TrainingTypesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/events/_form.html.haml
= simple_form_for(event, url: url) do |f|
	= f.input :title
	= f.input :description
	= f.input :date, as: :date_picker
	= f.association :event_type
	= f.association :season
	= f.button :submit

app/views/events/_people_list.html.haml
.col-md-3
	%h3 #{title} (#{presences.size})
	%ol
	- presences.each do |presence|
		%li= link_to presence.member.full_name, presence.member

app/views/events/edit.html.haml
%h1= event_title(@event)
= render partial: 'form', locals: {event: @event, season: @season, url: season_event_path(@season, @event)}

app/views/events/new.html.haml
%h1= t('New training')
= render partial: 'form', locals: {event: @event, season: @season, url: season_events_path(@season)}

app/views/events/show.html.haml
%h1
	= @event.date
	%small (#{link_to t('edit'), edit_season_event_path(@event.season_id, @event)})

- unless @event.description.blank?
	= simple_format @event.description

.row
	= render partial: 'people_list', locals: {presences: @presences.select{|p| p.presence_type == 1}, title: t('training.present')}

	= render partial: 'people_list', locals: {presences: @presences.select{|p| p.presence_type == 4}, title: t('training.competition')}

	= render partial: 'people_list', locals: {presences: @presences.select{|p| p.presence_type == 3}, title: t('training.extenuated')}

	= render partial: 'people_list', locals: {presences: @presences.select{|p| p.presence_type == 2}, title: t('training.absent')}

app/views/members/_attendance_simple.html.haml
%p
	%strong #{t('Attendance').html_safe}:
	= number_to_percentage(attendance[:obligatory], precision: 2)
	- if attendance[:obligatory] != attendance[:all]
		(#{number_to_percentage(attendance[:all])})

app/views/members/_form.html.haml
= simple_form_for(member, html: {class: 'form-horizontal'}) do |f|
	= f.input :first_name
	= f.input :last_name
	= f.input :sex, collection: { male: 0, female: 1 }
	= f.input :active, wrapper: :checkbox
	= f.input :active_since
	
	= f.button :submit

app/views/members/index.html.haml
%h1= t('Members')
%p
	=icon('plus')
	= link_to t('member.Add member'), new_member_path
.table-responsive
	%table.table.table-striped
		%thead
			%tr
				%th= t('member.Name')
				%th= t('member.Sex')
				%th= t('member.Active')
				%th= t('administration')
		%tbody
			- @members.each do |member|
				%tr
					%td= link_to "#{member.last_name} #{member.first_name}", member
					%td= format_sex(member.sex)
					%td= member.active
					%td
						= link_to icon('edit'), edit_member_path(member)
						&middot;
						= link_to icon('trash-o'), member_path(member), data: {confirm: 'Are you sure?'}, method: 'delete'

app/views/members/new.html.haml
=render partial: 'form', locals: {member: @member}

app/views/members/show.html.haml
%h1= @member.full_name

.row
	.col-md-6
		%h3= t('Events')
		%table.table
			%thead
				%tr
					%th= t('Date')
					%th= t('Type')
					%th= t('Presence')
			%tbody
				= raw render(format_attendances(@attendance))
				- @presences.each do |presence|
					%tr{:class => Presence::PRESENCE_TYPES[presence.presence_type].downcase}
						%td= link_to presence.event.date, season_event_path(presence.event.season_id, presence.event)
						%td= t(presence.event.event_type.name)
						%td= t(Presence::PRESENCE_TYPES[presence.presence_type])

	.col-md-6
		%h3= t('Teams')
		%table.table
			%tbody
				- @member.team_memberships.order(start: :desc).includes(:team).each do |membership|
					%tr
						%td= link_to membership.team.name, membership.team
						%td
							= membership.start
							&dash;
							= membership.finish

app/views/seasons/_form.html.haml
= simple_form_for(season) do |f|
	= f.input :name
	= f.input :start
	= f.button :submit

app/views/seasons/attendances.html.haml
%h1= t('season.header', name: @season.name)
.possibly-wide
	%table.table.table-condensed.table-bordered#attendance-table
		%thead
			%tr
				%th{class: 'sortable'}= t('member.name')
				%th{class: 'sortable'}= t('member.attendance')
				- @season.events.each do |training|
					%th= link_to training.date.strftime("%d.%m"), season_event_path(@season, training)
		%tbody
			- @member_presences.each do |member_row|
				%tr
					%td= link_to "#{member_row[:member].last_name}&nbsp;#{member_row[:member].first_name}".html_safe, member_row[:member]
					%td= number_to_percentage(member_row[:attendance], precision: 2)
					- member_row[:presence].each do |presence|
						%td{class: presence_class(presence)}= format_presence(presence)

:javascript
	$(document).ready(function() {
		var table = $('#attendance-table').dataTable({
			"bPaginate": false,
			"bSort": false,
			"bFilter": true,
			"bAutoWidth": false,
			"bInfo": false,
			"aoColumnDefs" : [ {
				'bSortable' : true,
				'aTargets' : [ 'sortable' ]
			} ]
		});
		//new $.fn.dataTable.FixedHeader( table, {offsetTop: 50, left: true} );
	});

app/views/seasons/edit.html.haml
%h1 #{t('Editing')} #{@season.name}
=render partial: 'form', locals: {season: @season}

app/views/seasons/index.html.haml
%h1= t('Seasons')
%p
	=icon('plus')
	= link_to t('seasopn.Add season'), new_season_path
.table-responsive
	%table.table.table-striped
		%thead
			%tr
				%th= t('season.Name')
				%th= t('season.Start date')
				%th= t('administration')
		%tbody
			- @seasons.each do |season|
				%tr
					%td= link_to season.name, season
					%td= l(season.start)
					%td
						= link_to icon('edit'), edit_season_path(season)
						&middot;
						= link_to icon('trash-o'), season_path(season), method: 'delete'

app/views/seasons/new.html.haml
%h1= t('New season')
= render partial: 'form', locals: {season: @season}

app/views/seasons/show.html.haml
%h1
	= t('Season')
	= @season.name

%ul.list-inline.big-font
	%li= t('season.attendances') + ":"
	- @event_types.each do |type|
		%li= link_to type.name, attendances_season_path(@season, type: type.id)
	%li= link_to t('attendance.all'), attendances_season_path(@season)

.row
	.col-md-6
		%h2= t('season.events')

		%p
			=icon('plus')
			= link_to t('events.New'), new_season_event_path(@season)

		%table.table
			%thead
				%tr
					%th= t('event.name')
					%th= t('event.type')
					%th= t('event.date')
			%tbody
				- @events.each do |event|
					%tr
						%td= link_to event_title(event), season_event_path(event.season_id, event)
						%td= t(event.event_type.name)
						%td= l(event.date)


	.col-md-6
		%h2= t('season.competitions')