config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    resources :team_memberships
  end

  resources :presences

  resources :training_types

  resources :seasons do
  	resources :events
  	get :attendances, :on => :member
  end

  resources :members

  root to: 'home#index'

  devise_for :users
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
	belongs_to :team
	belongs_to :member

	def active?
		now = Time.now
		(start.nil? || start < now) && (finish.nil? || finish > now)
	end

	# if no start date is given it is assumed that it is equal
	# to team founding date
	def start
		attribute(:start) || self.team.founded
	end
end

app/controllers/team_memberships_controller.rb
class TeamMembershipsController < ApplicationController
  def index
    @team = Team.find(params[:team_id])
    @memberships = @team.team_memberships
  end

  def create
    @team = Team.find(params[:team_id])
    @team.team_memberships.create(safe_params)
    redirect_to @team
  end

  def edit
    @membership = TeamMembership.find(params[:id])
  end

  def update
    @membership = TeamMembership.find(params[:id])
    if @membership.update_attributes(safe_params)
      redirect_to team_path(@membership.team_id)
    else
      render :edit
    end
  end

  def destroy
    @membership = TeamMembership.find(params[:id])
    @membership.destroy
    redirect_to team_path(@membership.team_id)
  end

  private
  def safe_params
    params.require(:team_membership).permit(:start, :finish, :member_id)
  end
end

app/helpers/team_memberships_helper.rb
module TeamMembershipsHelper
end

app/views/team_memberships/edit.html.haml
= simple_form_for @membership, url: team_team_membership_path(@membership.team_id, @membership) do |f|
  = f.association :member, label_method: :full_name, as: :select, input_html: {class: 'select2'}
  = f.input :start, as: :date_picker
  = f.input :finish, as: :date_picker
  = f.button :submit

app/views/team_memberships/index.html.haml
%h1 Members of #{@team.name}

%table.table
  %thead
    %tr
      %th= t('member.name')
      %th= t('membership.start')
      %th= t('membership.finish')
      %th= t('administration')
  %tbody
    - @memberships.each do |membership|
      %tr
        %td= link_to membership.member.full_name, member_path(membership.member)
        %td= membership.start
        %td= membership.finish
        %td= administration_links(edit: edit_team_team_membership_path(@team, membership),
          delete: team_team_membership_path(@team, membership))